version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: gilito-minio
    ports:
      - "9000:9000"     # interfaz de MinIO
      - "9001:9001"     # consola web
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data
    command: server --console-address ":9001" /data

volumes:
  minio-data:
