name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: run docker containers
        run: docker compose up -d
      - name: wait for containers to be ready
        run: sleep 10
      - name: npm install
        run: |
          npm install
      - name: npm run lint
        run: |
          npm run lint
      - name: Configurar MinIO (crear buckets, etc.)
        run: npm run configure:minio
      - name: npm run build
        run: |
          npm run build --if-present
      - name: npm run test:unit
        run: |
          npm run test:unit
      - name: npm run test:features
        run: |
          npm run test:features